
delete from enrollments WHERE true;
ALTER TABLE enrollments AUTO_INCREMENT = 1;
delete from faculty WHERE true;
ALTER TABLE faculty AUTO_INCREMENT = 1;
delete from grade_scale WHERE true;
ALTER TABLE grade_scale AUTO_INCREMENT = 1;
delete from marks WHERE true;
ALTER TABLE marks AUTO_INCREMENT = 1;
delete from notifications WHERE true;
ALTER TABLE notifications AUTO_INCREMENT = 1;
delete from programmes WHERE true;
ALTER TABLE programmes AUTO_INCREMENT = 1;
delete from results WHERE true;
ALTER TABLE results AUTO_INCREMENT = 1;
delete from result_publication WHERE true;
ALTER TABLE result_publication AUTO_INCREMENT = 1;
delete from semesters WHERE true;
ALTER TABLE semesters AUTO_INCREMENT = 1;
delete from students WHERE true;
ALTER TABLE students AUTO_INCREMENT = 1;
delete from subjects WHERE true;
ALTER TABLE subjects AUTO_INCREMENT = 1;
delete from subject_allocations WHERE true;
ALTER TABLE subject_allocations AUTO_INCREMENT = 1;
delete from transcript_requests WHERE true;
ALTER TABLE transcript_requests AUTO_INCREMENT = 1;
delete from users WHERE true;
ALTER TABLE users AUTO_INCREMENT = 1;
